server:
  port: xxx


spring:

  redis:
    host: xxx
    port: 6379
    # 超时时间
    timeout: 10000ms
    # 数据库
    database: 0
    lettuce:
      pool:
        # 最大连接数
        max-active: 1024
        # 最大连接阻塞等待时间
        max-wait: 10000ms
        # 最大/小空闲连接
        max-idle: 200
        min-idle: 5

  datasource:
    # 数据库访问配置，使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxx:xxx/xxx?serverTimezone=Asia/Shanghai
    username: xxx
    password: xxx

    druid:
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20

      # 连接等待超时时间
      max-wait: 30000

      # 配置检测可以关闭的空闲连接间隔时间
      timeBetweenEvictionRunsMillis: 60000

      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000

      # 用来检测连接是否有效的sql，要求是一个查询语句。
      validation-query: select '1' from dual

      # 建议配置为true，不影响性能，并且保证安全性。
      # 如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-return: false
      # 打开PSCache并且指定每个连接上PSCache的大小
      # 即是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      pool-prepared-statements: false
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat
      # Spring监控AOP切入点，如x.y.z.service.*，配置多个用 英文逗号分隔
      aop-patterns: cn.ean.emp.service.*

      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      # StatViewServlet配置
      stat-view-servlet:
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台
        login-username: druid
        login-password: druid123
        # IP白名单
        # allow: 127.0.0.1
        # IP黑名单（共同存在时，deny优先于allow）
        # deny: 192.168.1.218

      # 配置StatFilter
      filter:
        stat:
          log-slow-sql: true


  rabbitmq:
    # 用户名
    username: xxxx
    # 密码
    password: xxxx
    # 服务器地址
    host: xxxx
    # 端口
    port: 5672
    #消息确认回调
    publisher-confirm-type: correlated
    #消息失败回调
    publisher-returns: true

  thymeleaf:
    cache: false






mybatis-plus:
  # type-aliases扫描路径
  #  type-aliases-package: cn.ean.emp.model.po
  # mapper xml实现扫描路径
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
    #property:
    #order: BEFORE

logging:
  level:
    cn.ean.emp.mapper: debug

jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT加解密使用的密钥
  secret: xxxxx
  # JWT的超期限时间 (60*60*24)
  expiration: 604800
  # JWT负载中拿到开头
  tokenHead: Bearer
